### ISSUE TITLE
Is the dataset publicly available?

### ISSUE THREAD

**Issue by mwang98** [JD-AI-Research-NLP/RevCore#1]
I was wondering if you would release the review-augmented dataset and authorize me to share them with me on the Google drive.

**Comment by luyulalalala** [comment]
Thanks for your interest. Actually,  RevCore mainly  focus on a review-augmented method rather than a dataset. We can provide the reviews crawled one year ago,  however, we recommend  you can crawl it in the way described in our paper, even in other domain, like restaurant, traveling, etc., for conversational recommendation.
By the way, I have send the reviews to your email box.

**Comment by Oran-Ac** [comment]
Hi there, I am also interested in your work and want to  have a try with your work. Could you also share a copy of reviews with me. Thanks a lot!

**Comment by Mingming1998** [comment]
Could you share a copy of reviews with me? Thanks a lot.

**Comment by luyulalalala** [comment]
> Could you share a copy of reviews with me? Thanks a lot.

**Comment by wxl1999** [comment]
@mwang98 Hi, can you share the review-augmented dataset with me?

**Comment by YTZ01** [comment]
@mwang98 Hello, can you share the review-augmented dataset? my email is zyt429nemo@163.com.
Thanks!

**Comment by YTZ01** [comment]
> @mwang98 Hi, can you share the review-augmented dataset with me?

@wxl1999 Hi, did you receive the review-augmented dataset? Can you share it with me. email: zyt429nemo@163.com.
Thanks!
